///////////////////////////////////////////////////////////////////////////////
// SMPTE_TimecodeClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "SMPTE_TimecodeClassFactory.h"
#include "SMPTE_TimecodeServices.h"
#include "SMPTE_TimecodeVersion.h"
#include "Timecode_Receiver.h"

BEGIN_CLASS_MAP(CSMPTE_TimecodeClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_SMPTE_Timecode, CID_SMPTE_TimecodeCTimecode_Receiver, SRVNAME_SMPTE_TIMECODE "!CTimecode_Receiver", CTimecode_Receiver)
///</AutoGeneratedContent>
END_CLASS_MAP()

CSMPTE_TimecodeClassFactory::CSMPTE_TimecodeClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_SMPTE_TIMECODE));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(SMPTE_Timecode));
#endif //defined(TCDBG_UNIT_VERSION)
}

