///////////////////////////////////////////////////////////////////////////////
// SMPTE_TimecodeInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "SMPTE_TimecodeServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
