///////////////////////////////////////////////////////////////////////////////
// SMPTE_TimecodeServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_SMPTE_Timecode = 0x3F000000;
#define SRVNAME_SMPTE_TIMECODE "SMPTE_Timecode"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_SMPTE_TimecodeCTimecode_Receiver = {0xc01a0628,0xc903,0x3e25,{0x20,0xa5,0x93,0x61,0x9f,0xa8,0x37,0xac}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#pragma pack(push,1)
typedef struct _Timecode_ReceiverInputs
{
	SHORT EL3702_Sample[100];
	bool Reset_Frame_Count;
} Timecode_ReceiverInputs, *PTimecode_ReceiverInputs;
#pragma pack(pop)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_000100000100_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_000100000100_INCLUDED_
typedef CHAR STRING256[257];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_000100000100_INCLUDED_)

#pragma pack(push,1)
typedef struct _Timecode_ReceiverOutputs
{
	float Frame_Rate;
	SHORT Frames_Units;
	SHORT Frames_Tens;
	SHORT Frames;
	SHORT Seconds_Units;
	SHORT Seconds_Tens;
	SHORT Seconds;
	SHORT Minutes_Units;
	SHORT Minutes_Tens;
	SHORT Minutes;
	SHORT Hours_Units;
	SHORT Hours_Tens;
	SHORT Hours;
	STRING256 Time_String;
	DWORD Frame_Count;
	WORD Index_Tab_EL3702_Error;
	WORD Index_Tab_Timecode_Frame_Error;
	DWORD Frame_Error;
	HRESULT Timecode_Receiver_Status;
} Timecode_ReceiverOutputs, *PTimecode_ReceiverOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Timecode_ReceiverInputs 0
#define ADI_Timecode_ReceiverOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
